# Generated by Django 5.2.17 on 2026-09-03 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0003_alter_encounter_current_department_and_more'),
        ('patients', '0002_patient_is_nhif_patient_nhif_card_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RCHClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_type', models.CharField(choices=[('MOTHER', 'Mother / woman of reproductive age'), ('CHILD', 'Child / under-5')], db_index=True, default='MOTHER', max_length=10)),
                ('gravida', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('para', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('abortions', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('living_children', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('hiv_status', models.CharField(blank=True, help_text='Unknown / Negative / Positive / Declined', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rch_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(blank=True, help_text='Mother patient record for this child', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rch_children', to='patients.patient')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rch_profile', to='patients.patient')),
            ],
            options={
                'verbose_name': 'RCH client profile',
                'verbose_name_plural': 'RCH client profiles',
            },
        ),
        migrations.CreateModel(
            name='RCHVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('ANC', 'Antenatal care (ANC)'), ('PNC', 'Postnatal care (PNC)'), ('UNDER5', 'Under-5 / child health'), ('IMMUNIZATION', 'Immunization'), ('FP', 'Family planning'), ('NUTRITION', 'Nutrition'), ('OTHER', 'Other RCH')], db_index=True, max_length=20)),
                ('visit_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('next_appointment', models.DateField(blank=True, db_index=True, null=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('is_high_risk', models.BooleanField(db_index=True, default=False)),
                ('attended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rch_visits_attended', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rch_visits_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rch_visit', to='encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rch_visits', to='patients.patient')),
            ],
            options={
                'verbose_name': 'RCH visit',
                'verbose_name_plural': 'RCH visits',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PNCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_postpartum', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mother_bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mother_bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mother_condition', models.TextField(blank=True)),
                ('bleeding', models.CharField(blank=True, max_length=50)),
                ('breastfeeding', models.CharField(blank=True, max_length=50)),
                ('baby_condition', models.TextField(blank=True)),
                ('baby_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('counselling', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('rch_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pnc', to='rch.rchvisit')),
            ],
            options={
                'verbose_name': 'PNC record',
                'verbose_name_plural': 'PNC records',
            },
        ),
        migrations.CreateModel(
            name='ImmunizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine', models.CharField(choices=[('BCG', 'BCG'), ('OPV0', 'OPV-0'), ('OPV1', 'OPV-1'), ('OPV2', 'OPV-2'), ('OPV3', 'OPV-3'), ('PENTA1', 'Penta-1'), ('PENTA2', 'Penta-2'), ('PENTA3', 'Penta-3'), ('PCV1', 'PCV-1'), ('PCV2', 'PCV-2'), ('PCV3', 'PCV-3'), ('ROTA1', 'Rota-1'), ('ROTA2', 'Rota-2'), ('ROTA3', 'Rota-3'), ('IPV', 'IPV'), ('MEASLES1', 'Measles-1'), ('MEASLES2', 'Measles-2'), ('TT', 'TT / Td'), ('HPV', 'HPV'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('vaccine_other', models.CharField(blank=True, help_text='If vaccine=OTHER', max_length=100)),
                ('dose_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immunizations_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='patients.patient')),
                ('rch_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='rch.rchvisit')),
            ],
            options={
                'verbose_name': 'Immunization record',
                'verbose_name_plural': 'Immunization records',
                'ordering': ['-dose_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyPlanningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(blank=True, choices=[('PILL', 'Oral pill'), ('INJECTABLE', 'Injectable'), ('IMPLANT', 'Implant'), ('IUD', 'IUD'), ('CONDOM', 'Condom'), ('NATURAL', 'Natural / LAM'), ('STERILIZATION', 'Sterilization'), ('OTHER', 'Other')], max_length=20)),
                ('method_provided', models.BooleanField(default=False, help_text='Method was issued/provided this visit')),
                ('previous_method', models.CharField(blank=True, max_length=50)),
                ('side_effects', models.TextField(blank=True)),
                ('counselling_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('rch_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fp', to='rch.rchvisit')),
            ],
            options={
                'verbose_name': 'Family planning record',
                'verbose_name_plural': 'Family planning records',
            },
        ),
        migrations.CreateModel(
            name='ANCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lmp', models.DateField(blank=True, help_text='Last menstrual period', null=True)),
                ('edd', models.DateField(blank=True, help_text='Expected date of delivery', null=True)),
                ('gestational_age_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anc_visit_number', models.PositiveSmallIntegerField(blank=True, help_text='e.g. 1st, 2nd, 4th ANC visit', null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fetal_heart_rate', models.PositiveSmallIntegerField(blank=True, help_text='Beats per minute', null=True)),
                ('risk_factors', models.TextField(blank=True)),
                ('supplements', models.CharField(blank=True, help_text='e.g. Fe/FA, SP, calcium, ITN issued', max_length=255)),
                ('lab_notes', models.TextField(blank=True)),
                ('ultrasound_notes', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('rch_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anc', to='rch.rchvisit')),
            ],
            options={
                'verbose_name': 'ANC record',
                'verbose_name_plural': 'ANC records',
            },
        ),
        migrations.CreateModel(
            name='Under5Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('muac_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Mid-upper arm circumference (cm)', max_digits=4, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('nutrition_status', models.CharField(blank=True, help_text='e.g. Normal / MAM / SAM', max_length=50)),
                ('development_notes', models.TextField(blank=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('treatment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('rch_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='under5', to='rch.rchvisit')),
            ],
            options={
                'verbose_name': 'Under-5 record',
                'verbose_name_plural': 'Under-5 records',
            },
        ),
    ]
