# Generated by Django 5.2.17 on 2026-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancrecord',
            name='abdominal_circumference_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maternal abdominal circumference (cm)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ancrecord',
            name='expected_fetal_length_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Expected fetal length / height (cm), if recorded', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ancrecord',
            name='expected_fetal_weight_g',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated / expected fetal weight in grams', null=True),
        ),
        migrations.AddField(
            model_name='ancrecord',
            name='fundal_height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Symphysis–fundal height (cm)', max_digits=5, null=True),
        ),
    ]
