# Generated by Django 5.2.17 on 2026-08-28 11:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='encounters.encounter')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB', 'Laboratory'), ('RADIOLOGY', 'Radiology'), ('PHARMACY', 'Pharmacy'), ('WARD', 'Ward / Bed'), ('PROCEDURE', 'Procedure'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('INSURANCE', 'Insurance / NHIF'), ('MIXED', 'Mixed (Cash + Insurance)'), ('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Card')], db_index=True, default='CASH', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=15)),
                ('linked_service', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='encounters.encounter')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_number', models.CharField(db_index=True, max_length=50)),
                ('claim_status', models.CharField(choices=[('SUBMITTED_PENDING', 'Submitted – Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted')], db_index=True, default='SUBMITTED_PENDING', max_length=25)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claim', to='billing.payment')),
            ],
            options={
                'verbose_name': 'Insurance Claim',
                'verbose_name_plural': 'Insurance Claims',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_method'], name='billing_pay_status_40482b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['encounter', 'status'], name='billing_pay_encount_5ad6b1_idx'),
        ),
    ]
