# Generated by Django 5.2.17 on 2026-08-28 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_type', models.CharField(choices=[('OPD', 'Outpatient'), ('IPD', 'Inpatient')], db_index=True, default='OPD', max_length=3)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PAID_AWAITING_NURSE', 'Paid – Awaiting Nurse'), ('WITH_NURSE', 'With Nurse'), ('WITH_DOCTOR', 'With Doctor'), ('LAB_REQUESTED', 'Lab Requested'), ('RADIOLOGY_REQUESTED', 'Radiology Requested'), ('ADMITTED', 'Admitted'), ('PRESCRIBED', 'Prescribed'), ('PRESCRIPTION_WRITTEN', 'Prescription Written'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('IN_PROGRESS', 'In Progress'), ('RESULTS_READY', 'Results Ready'), ('PHARMACY_PAID', 'Pharmacy Paid'), ('MEDICINE_DISPENSED', 'Medicine Dispensed'), ('IN_WARD', 'In Ward'), ('SIGNED_OFF', 'Signed Off'), ('DISCHARGED', 'Discharged'), ('CANCELLED', 'Cancelled')], db_index=True, default='REGISTERED', max_length=30)),
                ('chief_complaint', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Encounter / Visit',
                'verbose_name_plural': 'Encounters / Visits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=15)),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='encounters.encounter')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vitals',
                'verbose_name_plural': 'Vitals',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status', 'created_at'], name='encounters__status_b44184_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'status'], name='encounters__patient_413993_idx'),
        ),
    ]
