# Generated by Django 5.2.17 on 2026-08-31 06:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('from_department', models.CharField(blank=True, max_length=20)),
                ('to_department', models.CharField(blank=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Visit Log',
                'verbose_name_plural': 'Visit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Visit / Encounter', 'verbose_name_plural': 'Visits / Encounters'},
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='encounters__status_b44184_idx',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='appointment',
        ),
        migrations.AddField(
            model_name='encounter',
            name='current_department',
            field=models.CharField(choices=[('RECEPTION', 'Reception'), ('DOCTOR', 'Doctor'), ('LAB', 'Laboratory'), ('ULTRASOUND', 'Ultrasound'), ('INJECTION', 'Injection Room'), ('RCH', 'RCH'), ('LABOUR_WARD', 'Labour Ward'), ('PHARMACY', 'Pharmacy')], db_index=True, default='RECEPTION', help_text='Which department currently owns this visit.', max_length=20),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('PAYMENT_PENDING', 'Payment Pending'), ('IN_PROGRESS', 'In Progress'), ('RESULTS_READY', 'Results Ready'), ('PRESCRIPTION_WRITTEN', 'Prescription Written'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REGISTERED', max_length=30),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='visit_type',
            field=models.CharField(default='OPD', help_text='OPD / RCH / LABOUR etc.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status', 'current_department'], name='encounters__status_a54eba_idx'),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='encounters.encounter'),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
