# Generated by Django 5.2.17 on 2026-09-01 04:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_visitlog_alter_encounter_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='current_department',
            field=models.CharField(choices=[('RECEPTION', 'Reception'), ('DOCTOR', 'Doctor'), ('LAB', 'Laboratory'), ('ULTRASOUND', 'Ultrasound'), ('INJECTION', 'Injection Room'), ('RCH', 'RCH'), ('LABOUR_WARD', 'Labour Ward'), ('PHARMACY', 'Pharmacy')], db_index=True, default='RECEPTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='visit_type',
            field=models.CharField(default='OPD', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in TZS', max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Mobile Money transaction ID', max_length=100)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_payments_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_payments', to='encounters.encounter')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visit Payment',
                'verbose_name_plural': 'Visit Payments',
                'ordering': ['-received_at'],
            },
        ),
    ]
