# Generated by Django 5.2.17 on 2026-09-04 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_alter_encounter_current_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='nhif_auth_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid in TZS (0 for NHIF release)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('NHIF', 'NHIF (no cash)')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Mobile Money transaction ID or NHIF auth code', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_logs_performed', to=settings.AUTH_USER_MODEL),
        ),
    ]
