# Generated by Django 5.2.17 on 2026-09-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0004_encounter_nhif_auth_code_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='current_department',
            field=models.CharField(choices=[('RECEPTION', 'Reception'), ('DOCTOR', 'Doctor'), ('LAB', 'Laboratory'), ('ULTRASOUND', 'Ultrasound'), ('INJECTION', 'Injection Room'), ('MINOR_SURGERY', 'Minor Surgery'), ('RCH', 'RCH'), ('LABOUR_WARD', 'Labour Ward'), ('PHARMACY', 'Pharmacy')], db_index=True, default='RECEPTION', max_length=20),
        ),
    ]
