# Generated by Django 5.2.17 on 2026-09-08 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0005_alter_encounter_current_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='e.g. 120/80', max_length=15),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='spo2',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Oxygen saturation %', null=True),
        ),
    ]
