# Generated by Django 6.0.5 on 2026-09-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0006_vitals_notes_alter_vitals_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('PAYMENT_PENDING', 'Payment Pending'), ('IN_PROGRESS', 'In Progress'), ('RESULTS_READY', 'Results Ready'), ('PRESCRIPTION_WRITTEN', 'Prescription Written'), ('ADMITTED', 'Admitted'), ('IN_WARD', 'In Ward'), ('DISCHARGED', 'Discharged'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REGISTERED', max_length=30),
        ),
    ]
