# Generated by Django 5.2.17 on 2026-09-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='category',
            field=models.CharField(choices=[('HEMATOLOGY', 'Hematology'), ('CHEMISTRY', 'Clinical Chemistry'), ('LIVER', 'Liver Function'), ('LIPID', 'Lipid Profile'), ('INFECTIOUS', 'Infectious / Serology'), ('HORMONE', 'Hormones & Others'), ('URINE_STOOL', 'Urine & Stool'), ('COAGULATION', 'Coagulation'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
    ]
