# Generated by Django 5.2.17 on 2026-09-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_alter_laborder_clinical_notes_alter_labtest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash price in TZS for this test (0 = enter amount manually)', max_digits=12),
        ),
    ]
