# Generated by Django 5.2.17 on 2026-09-01 09:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
        ('encounters', '0003_alter_encounter_current_department_and_more'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drugbatch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='drugbatch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='drugbatch',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='category',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='description',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='drug',
            name='form',
            field=models.CharField(blank=True, help_text='e.g. Tablet, Syrup, Capsule, Injection', max_length=50),
        ),
        migrations.AddField(
            model_name='drug',
            name='strength',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='drug',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drug',
            name='generic_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispense_records_created', to=settings.AUTH_USER_MODEL)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses_done', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_records', to='pharmacy.drug')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_records', to='encounters.encounter')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispense_records', to='consultations.prescription')),
            ],
            options={
                'verbose_name': 'Dispense Record',
                'verbose_name_plural': 'Dispense Records',
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.DeleteModel(
            name='Dispense',
        ),
        migrations.DeleteModel(
            name='DrugBatch',
        ),
    ]
