# Generated by Django 5.2.17 on 2026-09-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_dispenserecord_options_alter_drug_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, help_text='Nearest / batch expiry for alert purposes', null=True),
        ),
    ]
