# Generated by Django 5.2.17 on 2026-09-05 06:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_drug_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='pack_size',
            field=models.PositiveIntegerField(default=1, help_text='Units per pack/box (e.g. 100 tablets per box). Use 1 if N/A.'),
        ),
        migrations.AddField(
            model_name='drug',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cash price per unit (tablet/bottle) in TZS', max_digits=12),
        ),
        migrations.AlterField(
            model_name='drug',
            name='unit',
            field=models.CharField(default='tablet', help_text='Base unit for stock and price (tablet, bottle, vial)', max_length=30),
        ),
    ]
