# Generated by Django 5.2.17 on 2026-08-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, help_text='e.g. OPD, Laboratory, Pharmacy, RCH, Labour Ward', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Internal staff number (EMP-YYYY-NNNN).', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTION_PHARMACY', 'Reception / Pharmacy'), ('DOCTOR', 'Doctor'), ('LAB', 'Laboratory Staff'), ('ULTRASOUND', 'Ultrasound Staff'), ('INJECTION', 'Injection Room Staff'), ('RCH', 'RCH Staff'), ('LABOUR_WARD', 'Labour Ward Staff')], db_index=True, help_text='Determines what the user can see and do in the system.', max_length=30),
        ),
    ]
