# Generated by Django 6.0.5 on 2026-09-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_staffprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTION', 'Reception'), ('PHARMACY', 'Pharmacy'), ('DOCTOR', 'Doctor'), ('LAB', 'Laboratory'), ('ULTRASOUND', 'Ultrasound'), ('INJECTION', 'Injection Room'), ('RCH', 'RCH'), ('LABOUR_WARD', 'Labour Ward')], db_index=True, help_text='Determines what the user can see and do in the system.', max_length=30),
        ),
    ]
