# Generated by Django 5.2.17 on 2026-09-02 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['created_at'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='external_notes',
            field=models.CharField(blank=True, help_text='Optional note printed on external prescription.', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_dispensed',
            field=models.BooleanField(default=False, help_text='Set when clinic pharmacy has dispensed this line.'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='source',
            field=models.CharField(choices=[('IN_HOUSE', 'Dispense at this pharmacy'), ('EXTERNAL', 'External prescription (PDF)')], db_index=True, default='IN_HOUSE', help_text='In-house uses clinic stock; External is for outside pharmacies.', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='secondary_diagnosis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
