# Generated by Django 5.2.17 on 2026-09-08 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0004_encounter_nhif_auth_code_alter_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('INJECTION', 'Injection / IM-IV'), ('DRESSING', 'Wound dressing'), ('MINOR_SURGERY', 'Minor surgery'), ('SUTURE', 'Suturing'), ('INCISION_DRAINAGE', 'Incision & drainage'), ('OTHER', 'Other procedure')], db_index=True, default='INJECTION', max_length=30)),
                ('procedure_name', models.CharField(blank=True, help_text='e.g. Excision of lipoma, I&D abscess', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('materials_used', models.CharField(blank=True, max_length=255)),
                ('complications', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DONE', 'Completed'), ('CANCELLED', 'Cancelled')], default='DONE', max_length=20)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injection_services_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injection_services', to='encounters.encounter')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injection_services_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Injection / minor procedure',
                'verbose_name_plural': 'Injection / minor procedures',
                'ordering': ['-performed_at'],
            },
        ),
    ]
